
menu:
  - title: Homepage
    url: /
  - title: Timeline
    url: /time.html


favicon: /images/favicon.png

recommend:
  size: 8

prefile:
  excerpt: |
    <p>I'm interested in functional programming, FPGAs and neural networks</p>
copyright: |
  Design by
  <a href='https://tianhui.xin' target='_blank'>怪咖晨</a>
comment:
  gitalk:
    enable: true
    owner: you github repository owner
    repo: you github repository
    clientID: you github Client ID
    clientSecret: you github Client Secret
  gitment:
    enable: false
    owner: you github repository owner
    repo: you github repository
    clientID: you github Client ID
    clientSecret: you github Client Secret
