
menu:
  - title: 首页
    url: /
  - title: 关于我
    url: /about.html
  - title: 时间轴
    url: /time.html


favicon: /images/favicon.png

recommend:
  size: 8

prefile:
  excerpt: |
    <p>网名：一笑奈何。</p>
    <p>职业：JAVA软件工程师、前端软件工程师</p>
    <p>Email：homeanter@163.com</p>
  wechat: /images/wechat.png
copyright: |
  Design by
  <a href='https://tianhui.xin' target='_blank'>怪咖晨个人博客</a>
  京ICP备16046477号-1
comment:
  gitment:
    enable: true
    owner: homeant
    repo: fun.tianhui.xin
    clientID: c36cc614c567adeadfb5
    clientSecret: 341ad3eeab7c19c58db6786935eb8cc4d0b98263
